version: "3.9"
services:
  front:
    # container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - kingspan-network
networks:
  kingspan-network:
    driver: bridge
